"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { z } from "zod";
import { creatures } from "@/lib/data";
import { db } from "@/lib/db";
import { earned, levelForXp, progress, xpUntilNext } from "@/lib/game";
import { flushQueue } from "@/lib/sync";
import type { Creature, LocalPhoto, Profile, QueueAction } from "@/lib/types";

const initial:Profile={id:"guest-local",displayName:"Explorador",totalXp:0,level:1,discoveries:[],favoriteIds:[],completedMissionIds:[],achievementIds:[],updatedAt:new Date().toISOString()};
const qrSchema=z.string().regex(/^MUSEO:\/\/CREATURE\/[A-Z0-9_]+$/);
const uid=()=>crypto.randomUUID();
export function MuseumApp(){
 const [profile,setProfile]=useState<Profile>(initial),[tab,setTab]=useState<"home"|"map"|"scan"|"collection"|"field">("home"),[online,setOnline]=useState(true),[pending,setPending]=useState(0),[photos,setPhotos]=useState<LocalPhoto[]>([]),[selected,setSelected]=useState<Creature|null>(null),[notice,setNotice]=useState<string|null>(null),[expedition,setExpedition]=useState(false); const input=useRef<HTMLInputElement>(null);
 const save=async(p:Profile, action?:QueueAction)=>{setProfile(p);await db.profile.put(p);if(action)await db.syncQueue.put(action);setPending(await db.syncQueue.where("synced").equals(0).count())};
 const refresh=async()=>{const p=await db.profile.get("guest-local");if(p)setProfile(p);setPhotos(await db.photos.toArray());setPending(await db.syncQueue.where("synced").equals(0).count())};
 useEffect(()=>{refresh(); const handle=()=>setOnline(navigator.onLine);handle();addEventListener("online",handle);addEventListener("offline",handle);if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js");return()=>{removeEventListener("online",handle);removeEventListener("offline",handle)}} ,[]);
 useEffect(()=>{if(online)flushQueue().then(refresh)},[online]);
 const discovered=useMemo(()=>creatures.filter(c=>profile.discoveries.includes(c.id)),[profile]); const missions=progress(profile,photos.length); const levelEnd=xpUntilNext(profile.totalXp);
 const discover=async(c:Creature)=>{if(!c.downloaded){setNotice("Esta criatura no está descargada. Conéctate o añade su zona al Modo Expedición.");return} if(profile.discoveries.includes(c.id)){setSelected(c);return} const now=new Date().toISOString();let next={...profile,discoveries:[...profile.discoveries,c.id],totalXp:profile.totalXp+c.xp,updatedAt:now};const newly=earned(next,photos.length);next={...next,totalXp:next.totalXp+newly.reduce((n,a)=>n+a.xpReward,0),level:levelForXp(next.totalXp),achievementIds:[...next.achievementIds,...newly.map(a=>a.id)]}; const q:QueueAction={id:uid(),type:"CREATURE_DISCOVERED",payload:{creatureId:c.id,sourceEventId:uid()},createdAt:now,synced:false,retryCount:0}; await save(next,q);setSelected(c);setNotice(`Nueva criatura descubierta · +${c.xp} XP${newly.length?` · Logro: ${newly[0].name}`:""}`)};
 const scan=(raw:string)=>{const parsed=qrSchema.safeParse(raw.trim().toUpperCase());if(!parsed.success){setNotice("Código no reconocido. Usa el formato MUSEO://CREATURE/ID.");return}const id=parsed.data.split("/").pop()!.toLowerCase();const c=creatures.find(x=>x.id===id);if(!c){setNotice("Este QR no pertenece a una criatura registrada.");return}discover(c)};
 const photo=async(e:React.ChangeEvent<HTMLInputElement>)=>{const blob=e.target.files?.[0];if(!blob)return;const item:LocalPhoto={id:uid(),creatureId:selected?.id,blob,status:"PENDING_UPLOAD",createdAt:new Date().toISOString()};await db.photos.put(item);await db.syncQueue.put({id:uid(),type:"PHOTO_CREATED",payload:{photoId:item.id,creatureId:item.creatureId},createdAt:item.createdAt,synced:false,retryCount:0});await refresh();setNotice("Fotografía guardada localmente y encolada para subir.")};
 const toggleFav=async(id:string)=>{const found=profile.favoriteIds.includes(id);await save({...profile,favoriteIds:found?profile.favoriteIds.filter(x=>x!==id):[...profile.favoriteIds,id],updatedAt:new Date().toISOString()},{id:uid(),type:"PROFILE_UPDATED",payload:{favoriteId:id},createdAt:new Date().toISOString(),synced:false,retryCount:0})};
 return <main className="mx-auto min-h-screen max-w-md bg-sand pb-24"><header className="bg-ink px-5 pb-7 pt-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs tracking-[.22em] text-lime">MUSEO INTERACTIVO</p><h1 className="font-display text-3xl">Expedición</h1></div><button onClick={()=>flushQueue().then(refresh)} className="rounded-full border border-white/20 px-3 py-1 text-xs">{online?pending?`${pending} pendientes`:"Sincronizado":"Offline"}</button></div><div className="mt-5 h-2 overflow-hidden rounded bg-white/15"><div className="h-full bg-lime" style={{width:`${Math.min(100,profile.totalXp/levelEnd*100)}%`}}/></div><div className="mt-2 flex justify-between text-xs text-white/75"><span>Nivel {profile.level} · {profile.totalXp} XP</span><span>{discovered.length}/{creatures.length} hallazgos</span></div></header>
 <section className="p-4">{tab==="home"&&<Home profile={profile} discovered={discovered} expedition={expedition} onStart={()=>setTab("map")} onDownload={()=>setTab("field")} onScan={()=>setTab("scan")}/>} {tab==="map"&&<Map profile={profile} onCreature={discover}/>} {tab==="scan"&&<Scanner onScan={scan}/>} {tab==="collection"&&<Collection profile={profile} onSelect={setSelected}/>} {tab==="field"&&<Field expedition={expedition} setExpedition={setExpedition} photos={photos} missions={missions} profile={profile}/>}</section>
 <nav className="fixed bottom-0 left-1/2 flex w-full max-w-md -translate-x-1/2 justify-around border-t border-ink/10 bg-white px-2 py-3 text-[10px] text-moss">{([['home','⌂','Inicio'],['map','◫','Mapa'],['scan','⌁','Escanear'],['collection','◈','Colección'],['field','✦','Campo']] as const).map(([id,icon,label])=><button key={id} onClick={()=>setTab(id)} className={`flex min-w-12 flex-col items-center gap-1 ${tab===id?"font-bold text-ink":""}`}><b className="text-xl leading-none">{icon}</b>{label}</button>)}</nav>
 <AnimatePresence>{selected&&<CreatureModal creature={selected} favorite={profile.favoriteIds.includes(selected.id)} found={profile.discoveries.includes(selected.id)} onClose={()=>setSelected(null)} onFav={()=>toggleFav(selected.id)} onPhoto={()=>input.current?.click()}/>} {notice&&<motion.button initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0}} onClick={()=>setNotice(null)} className="fixed bottom-24 left-4 right-4 z-50 rounded-2xl bg-ink p-4 text-left text-sm text-white shadow-xl">{notice}<span className="ml-2 text-lime">Cerrar</span></motion.button>}</AnimatePresence><input ref={input} onChange={photo} accept="image/*" capture="environment" type="file" className="hidden"/></main>
}
function Home({profile,discovered,expedition,onStart,onDownload,onScan}:{profile:Profile;discovered:Creature[];expedition:boolean;onStart:()=>void;onDownload:()=>void;onScan:()=>void}){return <div className="space-y-4"><div className="card overflow-hidden"><div className="h-48 bg-[url('https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=1000&q=80')] bg-cover bg-center"/><div className="p-5"><p className="eyebrow">Bitácora de {profile.displayName}</p><h2 className="mt-1 font-display text-2xl">El museo te espera</h2><p className="mt-2 text-sm text-ink/70">Cada código revela una historia. Empieza por el mapa o apunta tu cámara a una placa.</p><button onClick={onStart} className="tap mt-4 w-full rounded-2xl bg-ink py-4 font-bold text-white">COMENZAR EXPEDICIÓN</button><button onClick={onScan} className="tap mt-2 w-full rounded-2xl border border-ink/20 py-3 font-bold">ESCANEAR UN QR</button></div></div><div className="grid grid-cols-2 gap-3"><div className="card p-4"><p className="eyebrow">Colección</p><b className="mt-2 block text-3xl">{discovered.length}<small className="text-base text-ink/40">/{creatures.length}</small></b><span className="text-xs text-ink/60">criaturas descubiertas</span></div><button onClick={onDownload} className="card p-4 text-left"><p className="eyebrow">Expedición</p><b className="mt-2 block">{expedition?"Disponible offline":"Preparar mochila"}</b><span className="text-xs text-ink/60">Paquetes y multimedia</span></button></div></div>}
function Map({profile,onCreature}:{profile:Profile;onCreature:(c:Creature)=>void}){const zones=[...new Set(creatures.map(c=>c.zone))];return <div><p className="eyebrow">Mapa del museo</p><h2 className="mb-4 font-display text-3xl">Elige una zona</h2><div className="space-y-3">{zones.map((z,i)=>{const list=creatures.filter(c=>c.zone===z),found=list.filter(c=>profile.discoveries.includes(c.id)).length;return <button onClick={()=>onCreature(list[0])} key={z} className="card tap w-full p-4 text-left" style={{background:`linear-gradient(115deg, #fff, ${i%2?"#e4f0c3":"#d9eee6"})`}}><div className="flex justify-between"><b>{z}</b><span>{found}/{list.length}</span></div><div className="mt-3 h-1.5 rounded bg-ink/10"><div className="h-full rounded bg-moss" style={{width:`${found/list.length*100}%`}}/></div><p className="mt-3 text-xs text-ink/65">{list.map(c=>c.commonName).join(" · ")}</p></button>})}</div></div>}
function Scanner({onScan}:{onScan:(v:string)=>void}){const [code,setCode]=useState("");return <div className="space-y-4"><p className="eyebrow">Escáner de campo</p><div className="flex aspect-square items-center justify-center rounded-3xl border-2 border-dashed border-moss bg-moss/10 p-8 text-center"><div><b className="text-5xl">⌁</b><p className="mt-4 font-display text-xl">Apunta a un QR</p><p className="mt-2 text-sm text-ink/60">Para este MVP, pega o escribe el código de la placa.</p></div></div><input value={code} onChange={e=>setCode(e.target.value)} placeholder="MUSEO://CREATURE/TRICERATOPS_01" className="w-full rounded-xl border border-ink/20 bg-white p-4 text-sm outline-moss"/><button onClick={()=>onScan(code)} className="tap w-full rounded-2xl bg-rust py-4 font-bold text-white">REGISTRAR DESCUBRIMIENTO</button></div>}
function Collection({profile,onSelect}:{profile:Profile;onSelect:(c:Creature)=>void}){return <div><p className="eyebrow">Archivo de especies</p><h2 className="mb-4 font-display text-3xl">Colección</h2><div className="grid grid-cols-2 gap-3">{creatures.map(c=>{const found=profile.discoveries.includes(c.id);return <button key={c.id} onClick={()=>onSelect(c)} className={`card overflow-hidden text-left ${found?"":"opacity-55 grayscale"}`}><div className="h-28 bg-cover bg-center" style={{backgroundImage:`url(${c.image})`}}/><div className="p-3"><b className="block text-sm">{found?c.commonName:"Registro bloqueado"}</b><span className="text-xs text-moss">{found?c.category:"Escanea para revelar"}</span></div></button>})}</div></div>}
function Field({expedition,setExpedition,photos,missions,profile}:{expedition:boolean;setExpedition:(x:boolean)=>void;photos:LocalPhoto[];missions:ReturnType<typeof progress>;profile:Profile}){return <div className="space-y-5"><div><p className="eyebrow">Modo Expedición</p><h2 className="font-display text-3xl">Tu mochila offline</h2></div><div className="card p-5"><div className="flex justify-between"><b>{expedition?"Disponible offline":"Aún no descargado"}</b><span className="text-moss">{expedition?"450 MB":"0 MB"}</span></div><p className="mt-2 text-sm text-ink/65">{expedition?"36 criaturas · 18 misiones · 42 imágenes · mapa completo":"Incluye datos, imágenes principales, misiones y mapa."}</p><button onClick={()=>setExpedition(!expedition)} className="tap mt-4 w-full rounded-xl bg-ink py-3 text-sm font-bold text-white">{expedition?"ELIMINAR PAQUETE":"DESCARGAR PAQUETE BÁSICO"}</button></div><div><h3 className="font-display text-xl">Misiones</h3><div className="mt-2 space-y-2">{missions.map(m=><div key={m.id} className="card p-3"><div className="flex justify-between text-sm"><b>{m.hidden&&m.current===0?"Misión secreta":m.title}</b><span>{m.current}/{m.target}</span></div><p className="mt-1 text-xs text-ink/60">{m.description} · +{m.xpReward} XP</p></div>)}</div></div><div><h3 className="font-display text-xl">Galería personal <span className="text-sm">({photos.length})</span></h3><div className="mt-2 grid grid-cols-3 gap-2">{photos.length?photos.map(p=><div key={p.id} className="rounded-xl bg-ink/10 p-2 text-[10px]">📷<br/>{p.status}</div>):<p className="text-sm text-ink/60">Aún no tomaste fotografías.</p>}</div></div><p className="text-xs text-ink/50">Nivel {profile.level} · los cambios se guardan en este dispositivo.</p></div>}
function CreatureModal({creature,favorite,found,onClose,onFav,onPhoto}:{creature:Creature;favorite:boolean;found:boolean;onClose:()=>void;onFav:()=>void;onPhoto:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-40 flex items-end bg-black/50" onClick={onClose}><motion.article initial={{y:400}} animate={{y:0}} exit={{y:400}} onClick={e=>e.stopPropagation()} className="max-h-[90vh] w-full overflow-y-auto rounded-t-[2rem] bg-sand"><div className="h-56 bg-cover bg-center" style={{backgroundImage:`linear-gradient(0deg,#10241f99,transparent),url(${creature.image})`}}><button onClick={onClose} className="m-4 rounded-full bg-white/90 px-3 py-1 text-sm">Cerrar</button></div><div className="p-5"><div className="flex justify-between gap-4"><div><p className="eyebrow">{creature.category} · {creature.period}</p><h2 className="font-display text-3xl">{found?creature.commonName:"Registro sin descubrir"}</h2><i className="text-sm">{found&&creature.scientificName}</i></div><button onClick={onFav} className="text-2xl">{favorite?"♥":"♡"}</button></div>{found?<><p className="mt-4 text-sm leading-6">{creature.description}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs">{[["Altura",creature.height],["Longitud",creature.length],["Peso",creature.weight]].map(([a,b])=><div key={a} className="rounded-xl bg-white p-3"><b className="block text-moss">{b}</b>{a}</div>)}</div><div className="mt-4 rounded-xl bg-lime/35 p-3 text-sm"><b>Dato de campo:</b> {creature.fact}</div><button onClick={onPhoto} className="tap mt-4 w-full rounded-xl bg-rust py-3 font-bold text-white">TOMAR FOTOGRAFÍA</button></>:<p className="mt-4 text-sm">Escanea su placa para desbloquear este registro.</p>}</div></motion.article></motion.div>}
