import type { Achievement, Creature, Mission } from "./types";
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=80`;
export const creatures:Creature[]=[
 {id:"triceratops_01",commonName:"Triceratops horridus",scientificName:"Triceratops horridus",category:"Herbívoro",period:"Cretácico tardío",weight:"9 t",height:"3 m",length:"9 m",diet:"Plantas",habitat:"Llanuras",description:"Un gigante acorazado con tres cuernos y una gran gola ósea.",fact:"Su cráneo podía medir más de dos metros.",image:img("photo-1530595467537-0b5996c41f2d"),zone:"Valle Cretácico",xp:50,downloaded:true},
 {id:"triceratops_baby",commonName:"Triceratops cría",scientificName:"Triceratops horridus",category:"Herbívoro",period:"Cretácico tardío",weight:"90 kg",height:"0.8 m",length:"1.5 m",diet:"Plantas",habitat:"Manada",description:"Una cría aún aprendiendo a usar sus cuernos.",fact:"Crecían muy rápido durante sus primeros años.",image:img("photo-1518709594023-6eab9bab7b23"),zone:"Valle Cretácico",xp:35,downloaded:true},
 {id:"tyrannosaurus_rex",commonName:"Tyrannosaurus rex",scientificName:"Tyrannosaurus rex",category:"Carnívoro",period:"Cretácico tardío",weight:"8 t",height:"4 m",length:"12 m",diet:"Carne",habitat:"Bosques",description:"El gran depredador del Cretácico norteamericano.",fact:"Su mordida fue una de las más potentes conocidas.",image:img("photo-1558008258-3256797b43f3"),zone:"Valle Cretácico",xp:70,downloaded:true},
 {id:"velociraptor",commonName:"Velociraptor",scientificName:"Velociraptor mongoliensis",category:"Carnívoro",period:"Cretácico tardío",weight:"15 kg",height:"0.5 m",length:"2 m",diet:"Carne",habitat:"Desierto",description:"Pequeño, ágil y cubierto de plumas.",fact:"Era bastante menor que su versión cinematográfica.",image:img("photo-1598439210625-88c6a7d9837a"),zone:"Laboratorio",xp:45,downloaded:true},
 {id:"stegosaurus",commonName:"Stegosaurus",scientificName:"Stegosaurus stenops",category:"Herbívoro",period:"Jurásico tardío",weight:"5 t",height:"4 m",length:"9 m",diet:"Plantas",habitat:"Llanuras",description:"Sus placas dorsales regulaban posiblemente su temperatura.",fact:"Su cerebro era del tamaño aproximado de una nuez.",image:img("photo-1549480017-d76466a4b7e8"),zone:"Jurásico",xp:55,downloaded:true},
 {id:"ankylosaurus",commonName:"Ankylosaurus",scientificName:"Ankylosaurus magniventris",category:"Herbívoro",period:"Cretácico tardío",weight:"8 t",height:"2 m",length:"8 m",diet:"Plantas",habitat:"Bosques",description:"Un tanque viviente cubierto de osteodermos.",fact:"Su cola terminaba en una pesada maza.",image:img("photo-1608889825103-eb5ed706fc64"),zone:"Valle Cretácico",xp:60,downloaded:true},
 {id:"brachiosaurus",commonName:"Brachiosaurus",scientificName:"Brachiosaurus altithorax",category:"Herbívoro",period:"Jurásico tardío",weight:"50 t",height:"13 m",length:"22 m",diet:"Plantas",habitat:"Bosques",description:"Uno de los animales terrestres más altos de todos los tiempos.",fact:"Sus patas delanteras eran más largas que las traseras.",image:img("photo-1560972552-aba3456b5564"),zone:"Jurásico",xp:80,downloaded:true},
 {id:"spinosaurus",commonName:"Spinosaurus",scientificName:"Spinosaurus aegyptiacus",category:"Carnívoro",period:"Cretácico",weight:"7 t",height:"5 m",length:"15 m",diet:"Peces",habitat:"Ríos",description:"Un extraordinario cazador adaptado al ambiente acuático.",fact:"Su vela pudo servir para exhibición o termorregulación.",image:img("photo-1607391846981-1e7e1e6c7c4b"),zone:"Delta",xp:75,downloaded:true},
 {id:"pteranodon",commonName:"Pteranodon",scientificName:"Pteranodon longiceps",category:"Volador",period:"Cretácico tardío",weight:"25 kg",height:"2 m",length:"7 m",diet:"Peces",habitat:"Costas",description:"Un reptil volador, no un dinosaurio.",fact:"Su envergadura superaba los seis metros.",image:img("photo-1540573133985-87b6da6d54a9"),zone:"Cielo",xp:50,downloaded:true},
 {id:"mosasaurus",commonName:"Mosasaurus",scientificName:"Mosasaurus hoffmannii",category:"Acuático",period:"Cretácico tardío",weight:"15 t",height:"4 m",length:"17 m",diet:"Carne",habitat:"Océano",description:"El superdepredador de los mares cretácicos.",fact:"Era un lagarto marino, emparentado con los varanos.",image:img("photo-1544551763-46a013bb70d5"),zone:"Océano",xp:85,downloaded:false},
 {id:"anomaly_alpha",commonName:"Anomalía Alfa",scientificName:"Specimen α",category:"Anomalía",period:"Desconocido",weight:"?",height:"?",length:"?",diet:"Energía",habitat:"Archivo sellado",description:"Una lectura biológica que desafía la clasificación.",fact:"Solo aparece bajo ciertas condiciones.",image:img("photo-1511497584788-876760111969"),zone:"Archivo",xp:120,downloaded:true},
 {id:"anomaly_omega",commonName:"Anomalía Omega",scientificName:"Specimen Ω",category:"Anomalía",period:"Desconocido",weight:"?",height:"?",length:"?",diet:"Desconocida",habitat:"Archivo sellado",description:"El último registro de la expedición.",fact:"Su señal no coincide con ninguna especie conocida.",image:img("photo-1531306728370-e2ebd9d7bb99"),zone:"Archivo",xp:150,downloaded:false}
];
export const missions:Mission[]=[
 {id:"first",title:"Primer hallazgo",description:"Escanea tu primera criatura.",type:"tutorial",target:1,current:0,xpReward:30,hidden:false,status:"active",metric:"discoveries"},
 {id:"five",title:"Expedición en marcha",description:"Descubre 5 criaturas.",type:"exploración",target:5,current:0,xpReward:100,hidden:false,status:"active",metric:"discoveries"},
 {id:"photos",title:"Ojo de campo",description:"Toma 5 fotografías.",type:"fotografía",target:5,current:0,xpReward:100,hidden:false,status:"active",metric:"photos"},
 {id:"secret",title:"Señal imposible",description:"Encuentra una anomalía secreta.",type:"secreta",target:1,current:0,xpReward:150,hidden:true,status:"active",metric:"anomalies"}
];
export const achievements:Achievement[]=[{id:"first",name:"Primer descubrimiento",description:"Registraste tu primera criatura.",icon:"✦",xpReward:25},{id:"explorer",name:"Explorador",description:"Descubriste 5 criaturas.",icon:"◈",xpReward:75},{id:"anomaly",name:"Cazador de anomalías",description:"Descubriste una señal anómala.",icon:"◉",xpReward:100},{id:"photographer",name:"Fotógrafo",description:"Tomaste 5 fotos.",icon:"◌",xpReward:75},{id:"collector",name:"Coleccionista",description:"Completaste la colección.",icon:"◆",xpReward:250}];
