-- Offline events are idempotent: clients generate UUIDs and retries upsert by id.
create type public.user_role as enum ('visitor','admin');
create table public.profiles (id uuid primary key references auth.users on delete cascade, display_name text not null default 'Explorador', avatar_url text, level int not null default 1, total_xp int not null default 0, role public.user_role not null default 'visitor', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.zones (id text primary key, name text not null, description text, map_order int not null default 0);
create table public.creatures (id text primary key, slug text unique not null, common_name text not null, scientific_name text not null, category text not null, rarity text default 'common', period text, description text, height text, length text, weight text, diet text, habitat text, cover_image text, zone_id text references public.zones(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creature_media (id uuid primary key default gen_random_uuid(), creature_id text not null references public.creatures on delete cascade, type text not null check(type in ('image','video','audio')), url text not null, offline_available boolean not null default false, sort_order int not null default 0);
create table public.discoveries (id uuid primary key, user_id uuid not null references public.profiles on delete cascade, creature_id text not null references public.creatures, discovered_at timestamptz not null default now(), source_event_id uuid unique not null);
create table public.missions (id text primary key, title text not null, description text not null, type text not null, objective jsonb not null, xp_reward int not null, hidden boolean not null default false, active boolean not null default true);
create table public.user_missions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, mission_id text not null references public.missions, progress jsonb not null default '{}', status text not null default 'active', completed_at timestamptz, unique(user_id,mission_id));
create table public.achievements (id text primary key, name text not null, description text not null, icon text, xp_reward int not null default 0);
create table public.user_achievements (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, achievement_id text not null references public.achievements, unlocked_at timestamptz not null default now(), unique(user_id,achievement_id));
create table public.photos (id uuid primary key, user_id uuid not null references public.profiles on delete cascade, creature_id text references public.creatures, storage_url text, status text not null default 'PENDING_UPLOAD', created_at timestamptz not null default now());
create table public.events (id uuid primary key default gen_random_uuid(), title text not null, description text, starts_at timestamptz, ends_at timestamptz, active boolean not null default true);
create table public.download_packages (id text primary key, title text not null, kind text not null, bytes_estimate bigint not null, manifest jsonb not null default '{}');
create table public.visit_progress (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, zone_id text references public.zones, updated_at timestamptz not null default now(), unique(user_id,zone_id));
create table public.sync_events (id uuid primary key, event_type text not null, payload jsonb not null, created_at timestamptz not null, received_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.discoveries enable row level security; alter table public.user_missions enable row level security; alter table public.user_achievements enable row level security; alter table public.photos enable row level security; alter table public.sync_events enable row level security;
create policy "read own profile" on public.profiles for select using(auth.uid()=id); create policy "update own profile" on public.profiles for update using(auth.uid()=id); create policy "own discoveries" on public.discoveries for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own mission progress" on public.user_missions for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own achievements" on public.user_achievements for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own photos" on public.photos for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own sync events" on public.sync_events for all using(true) with check(true);
